//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MiscMsgs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscMsgs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MiscMsgs", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aproved Amount Should be Grater Then Claim Amount.
        /// </summary>
        internal static string AprovedGraterThenClaim {
            get {
                return ResourceManager.GetString("AprovedGraterThenClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch already exists.
        /// </summary>
        internal static string branchAlreadyExist {
            get {
                return ResourceManager.GetString("branchAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type already exists.
        /// </summary>
        internal static string busAreaAlreadyExist {
            get {
                return ResourceManager.GetString("busAreaAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tblCity already exists.
        /// </summary>
        internal static string cityAlreadyExist {
            get {
                return ResourceManager.GetString("cityAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person already exists.
        /// </summary>
        internal static string contactPersonAlreadyExist {
            get {
                return ResourceManager.GetString("contactPersonAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country already exists.
        /// </summary>
        internal static string CountryAlreadyExist {
            get {
                return ResourceManager.GetString("CountryAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Location already exists.
        /// </summary>
        internal static string custLocAlreadyExist {
            get {
                return ResourceManager.GetString("custLocAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer already exists.
        /// </summary>
        internal static string customerAlreadyExist {
            get {
                return ResourceManager.GetString("customerAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer&apos;s Head Office already added.
        /// </summary>
        internal static string customerHOAlreadyExist {
            get {
                return ResourceManager.GetString("customerHOAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Already Exist.
        /// </summary>
        internal static string departmentAlreadyExist {
            get {
                return ResourceManager.GetString("departmentAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation Already Exist.
        /// </summary>
        internal static string designationAlreadyExist {
            get {
                return ResourceManager.GetString("designationAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Already Exist.
        /// </summary>
        internal static string divisionAlreadyExist {
            get {
                return ResourceManager.GetString("divisionAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date Should be Grater then Reference Date.
        /// </summary>
        internal static string EffdateGraterThenReffdate {
            get {
                return ResourceManager.GetString("EffdateGraterThenReffdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employ Already Exist.
        /// </summary>
        internal static string empAlreadyExist {
            get {
                return ResourceManager.GetString("empAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Employee have already taken the leaves in these days.
        /// </summary>
        internal static string EmpAlreadyTakenLeave {
            get {
                return ResourceManager.GetString("EmpAlreadyTakenLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Leave Type.
        /// </summary>
        internal static string EnterLeaveType {
            get {
                return ResourceManager.GetString("EnterLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date should be greater then Start Date.
        /// </summary>
        internal static string EnterValidDates {
            get {
                return ResourceManager.GetString("EnterValidDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Already has been uploaded.
        /// </summary>
        internal static string FileAlreadyExixt {
            get {
                return ResourceManager.GetString("FileAlreadyExixt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Found already exists.
        /// </summary>
        internal static string howFoundAlreadyExist {
            get {
                return ResourceManager.GetString("howFoundAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Already Exist.
        /// </summary>
        internal static string locationAlreadyExist {
            get {
                return ResourceManager.GetString("locationAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record found !!!!.
        /// </summary>
        internal static string NoRecord {
            get {
                return ResourceManager.GetString("NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password mismatched.
        /// </summary>
        internal static string oldPwdNotMatches {
            get {
                return ResourceManager.GetString("oldPwdNotMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity already exists.
        /// </summary>
        internal static string oppAlreadyExist {
            get {
                return ResourceManager.GetString("oppAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the opportunity.
        /// </summary>
        internal static string OppNotSelected {
            get {
                return ResourceManager.GetString("OppNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Product already exists.
        /// </summary>
        internal static string oppProdAlreadyExist {
            get {
                return ResourceManager.GetString("oppProdAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one product&apos;s status should be Won or In Progress from all products of this opportunity.
        /// </summary>
        internal static string OppProdProgWonInProgNone {
            get {
                return ResourceManager.GetString("OppProdProgWonInProgNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one product&apos;s status should be won.
        /// </summary>
        internal static string OppProdProgWonNone {
            get {
                return ResourceManager.GetString("OppProdProgWonNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;A Team Member is not selected.
        /// </summary>
        internal static string PnANotSelected {
            get {
                return ResourceManager.GetString("PnANotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit already exists.
        /// </summary>
        internal static string prodCatAlreadyExist {
            get {
                return ResourceManager.GetString("prodCatAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Series already exists.
        /// </summary>
        internal static string prodSubCatAlreadyExist {
            get {
                return ResourceManager.GetString("prodSubCatAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Title already exists.
        /// </summary>
        internal static string prodTitleAlreadyExist {
            get {
                return ResourceManager.GetString("prodTitleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type already exists.
        /// </summary>
        internal static string prodTypeAlreadyExist {
            get {
                return ResourceManager.GetString("prodTypeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total of Q1, Q2, Q3 and Q4 is not equal to Target Value Total.
        /// </summary>
        internal static string QuartersTotalCheck {
            get {
                return ResourceManager.GetString("QuartersTotalCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month target excedes from its quarter total.
        /// </summary>
        internal static string QuarterTotalCheck {
            get {
                return ResourceManager.GetString("QuarterTotalCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response at this stage has already been added into system.
        /// </summary>
        internal static string QuestionsDuplication {
            get {
                return ResourceManager.GetString("QuestionsDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Already Exist !!!.
        /// </summary>
        internal static string RecordExist {
            get {
                return ResourceManager.GetString("RecordExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region already exists.
        /// </summary>
        internal static string regionAlreadyExist {
            get {
                return ResourceManager.GetString("regionAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Target already exists.
        /// </summary>
        internal static string SalesTargetAlreadyExist {
            get {
                return ResourceManager.GetString("SalesTargetAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member target value cannot be greater than month target value.
        /// </summary>
        internal static string salesTargetEmployeeExceed {
            get {
                return ResourceManager.GetString("salesTargetEmployeeExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Team already exists.
        /// </summary>
        internal static string salesTeamAlreadyExist {
            get {
                return ResourceManager.GetString("salesTeamAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SBF already exists.
        /// </summary>
        internal static string sbfAlreadyExist {
            get {
                return ResourceManager.GetString("sbfAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section already exists.
        /// </summary>
        internal static string SectionAlreadyExist {
            get {
                return ResourceManager.GetString("SectionAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please first select the opportunity.
        /// </summary>
        internal static string selectOpportunity {
            get {
                return ResourceManager.GetString("selectOpportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment already exists.
        /// </summary>
        internal static string sgmntAlreadyExist {
            get {
                return ResourceManager.GetString("sgmntAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has uploaded successfully.
        /// </summary>
        internal static string UploadSuccess {
            get {
                return ResourceManager.GetString("UploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        internal static string userAlreadyExist {
            get {
                return ResourceManager.GetString("userAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank code/name already exists.
        /// </summary>
        internal static string userBankAlreadyExist {
            get {
                return ResourceManager.GetString("userBankAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group already exists.
        /// </summary>
        internal static string userGroupAlreadyExist {
            get {
                return ResourceManager.GetString("userGroupAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question already exists.
        /// </summary>
        internal static string userQuestionAlreadyExist {
            get {
                return ResourceManager.GetString("userQuestionAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role already exists.
        /// </summary>
        internal static string usrRoleAlreadyExist {
            get {
                return ResourceManager.GetString("usrRoleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Plan No already exists.
        /// </summary>
        internal static string visPlanAlreadyExist {
            get {
                return ResourceManager.GetString("visPlanAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Plan Detail already exists.
        /// </summary>
        internal static string visPlanDetAlreadyExist {
            get {
                return ResourceManager.GetString("visPlanDetAlreadyExist", resourceCulture);
            }
        }
    }
}
